# Generated by Django 6.0.5 on 2026-05-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message_body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
