# Generated by Django 6.0.5 on 2026-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_description_project_image_project_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='header_image',
            field=models.URLField(blank=True, help_text='URL to professional header image', max_length=500, null=True),
        ),
    ]
