# Generated by Django 6.0.5 on 2026-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_image_url_alter_service_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story_video', models.FileField(blank=True, null=True, upload_to='site_videos/')),
                ('our_story_image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
            ],
        ),
    ]
