# Generated by Django 6.0.5 on 2026-05-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
