# Generated by Django 6.0.5 on 2026-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology_stack',
            field=models.CharField(blank=True, help_text='Comma separated tags e.g. Django, React, AWS', max_length=200, null=True),
        ),
    ]
