# Generated by Django 6.0.5 on 2026-06-29 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_serviceitem_clientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={},
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='has_completed_setup',
            new_name='onboarding_completed',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='description',
            new_name='short_explanation',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nexo_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('DESIGN', 'Graphic & Print Design'), ('WRITING', 'Writing & Editorial'), ('ACADEMIC', 'Academic & Research Support'), ('DATA_TECH', 'Data & Tech Solutions'), ('MARKETING', 'Web & Digital Marketing'), ('BUSINESS', 'Business Strategy & Admin'), ('MULTIMEDIA', 'Education & Multimedia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
