# Generated by Django 6.0.5 on 2026-06-29 22:26

from django.db import migrations

def populate_services(apps, schema_editor):
    ServiceItem = apps.get_model('core', 'ServiceItem')
    
    services_data = [
        # DESIGN: Graphic & Print Design
        ('DESIGN', "Presentation slide design (PowerPoint, Google Slides, Canva)", "Professional design for visual slides, business presentations, and pitch decks."),
        ('DESIGN', "Book covers & eBook design", "Stunning cover designs and typesetting for print and digital publishing."),
        ('DESIGN', "Resume/CV design", "Modern, employer-friendly CV formatting and template design."),
        ('DESIGN', "Letterheads & company profiles", "Cohesive corporate branding, documentation templates, and business profiles."),
        ('DESIGN', "Posters and flyers", "Eye-catching promotional flyers and posters for events, products, or campaigns."),
        ('DESIGN', "Brochures & leaflets", "Multi-fold brochures and informative leaflets for corporate or public messaging."),
        ('DESIGN', "Certificates & awards", "Elegant custom design templates for certificates, tokens, and corporate awards."),
        ('DESIGN', "Menu design", "Visually structured, high-conversion menu designs for restaurants and cafes."),
        ('DESIGN', "Business cards", "Professional, high-impact business card layouts representing your brand identity."),
        ('DESIGN', "Stickers & digital artwork", "Creative stickers, custom icons, and digital art assets for online or print usage."),

        # WRITING: Writing & Editorial
        ('WRITING', "Article and blog writing", "SEO-optimized articles and engaging blog posts tailored to your audience."),
        ('WRITING', "Website content writing", "Compelling web copy including homepage, landing page, and about sections."),
        ('WRITING', "Copywriting (ads, product descriptions)", "High-conversion copy for advertisements, sales pages, and online products."),
        ('WRITING', "Scriptwriting (YouTube, podcasts, short films)", "Narrative and instructional scripts designed for engagement and flow."),
        ('WRITING', "Speech writing", "Custom, powerful speeches written to captivate audiences and deliver clear messages."),
        ('WRITING', "Story writing & creative fiction", "Original storytelling, creative writing, and high-impact fictional pieces."),
        ('WRITING', "Technical writing", "Clear and accurate manuals, API guides, and technical reference material."),
        ('WRITING', "Proposal & Grant writing", "Persuasive funding proposals, business pitches, and grant applications."),
        ('WRITING', "Editing & proofreading", "Thorough grammar correction, stylistic enhancement, and typo checking."),
        ('WRITING', "Rewriting & paraphrasing", "Sentence restructuring and quality improvement of existing written content."),

        # ACADEMIC: Academic & Research Support
        ('ACADEMIC', "Thesis & dissertation writing (guided/ethical support)", "Ethical structural support, literature reviews, and developmental feedback."),
        ('ACADEMIC', "Academic editing & formatting (APA, MLA, Chicago, Vancouver)", "Precision styling and publication formatting according to standard styles."),
        ('ACADEMIC', "Research summaries & abstracts", "Concise summaries of papers, journals, and executive abstracts."),
        ('ACADEMIC', "Referencing & citation management", "Accurate cataloging of bibliography and citation items in document text."),
        ('ACADEMIC', "Research proposals", "Structured frameworks outlining objectives, methodologies, and hypotheses."),
        ('ACADEMIC', "Plagiarism checking & reduction", "Verification of work originality and rewriting to reduce duplication index."),
        ('ACADEMIC', "PowerPoint presentations for research defense", "Polished, academic slides structured for thesis defense panels."),
        ('ACADEMIC', "Research publication preparation", "Refining research manuscripts to align with target journal requirements."),
        ('ACADEMIC', "Systematic reviews & scoping reviews", "Comprehensive mapping and synthesis of research literature."),
        ('ACADEMIC', "Academic poster design", "Visually engaging, clean research posters optimized for scientific conferences."),

        # DATA_TECH: Data & Tech Solutions
        ('DATA_TECH', "Data entry", "Accurate database entry, spreadsheet populating, and administrative support."),
        ('DATA_TECH', "Basic programming (Python, R, SQL)", "Custom code scripts, automated commands, and database querying."),
        ('DATA_TECH', "Automation scripts", "Process automation for workflows, file scraping, and daily routine tasks."),
        ('DATA_TECH', "Data cleaning", "Standardizing records, handling missing data values, and formatting sets."),
        ('DATA_TECH', "Excel spreadsheet creation", "Functional sheets using advanced calculations, pivot tables, and dashboards."),
        ('DATA_TECH', "Database management", "Designing, configuring, and optimizing relational databases and queries."),
        ('DATA_TECH', "Data collection & survey design", "Gathering data inputs and drafting online/offline survey questionnaires."),
        ('DATA_TECH', "Questionnaire development", "Structuring targeted data gathering forms and feedback questions."),
        ('DATA_TECH', "Data analysis (SPSS, Stata, R, Excel)", "Extracting statistical insights and processing raw data."),
        ('DATA_TECH', "Statistical interpretation", "Formulating mathematical hypotheses and describing data trends clearly."),

        # MARKETING: Web & Digital Marketing
        ('MARKETING', "Website design (WordPress, Wix, HTML/CSS)", "Designing and deploying responsive, modern corporate websites."),
        ('MARKETING', "UI/UX design", "Creating beautiful wireframes and intuitive web/app interfaces in Figma."),
        ('MARKETING', "SEO optimization", "On-page, technical, and off-page optimization to improve Google rankings."),
        ('MARKETING', "Landing page creation", "High-converting, optimized lead capture pages to support ad campaigns."),
        ('MARKETING', "Domain & hosting setup", "Assisting with server deployment, domain registration, and SSL certificates."),
        ('MARKETING', "Website testing & debugging", "Comprehensive checks to locate usability issues, speed bottlenecks, and code bugs."),
        ('MARKETING', "Social media management", "Content scheduling, visual designs, and profile optimization for social channels."),
        ('MARKETING', "Digital ad design (Facebook, Google Ads)", "Creating visual graphics and ad copy to maximize click-through rates."),
        ('MARKETING', "Email marketing campaigns", "Designing templates and copywriting for high-conversion newsletter campaigns."),
        ('MARKETING', "Content strategy development", "Building content roadmaps to reach target audiences organically."),

        # BUSINESS: Business Strategy & Admin
        ('BUSINESS', "Business reports", "Writing thorough summaries, company documentation, and quarterly reviews."),
        ('BUSINESS', "Business plan writing", "Developing business roadmaps, market outlines, and operational plans."),
        ('BUSINESS', "Pitch deck creation", "Professional slides designed for raising venture capital and angel funding."),
        ('BUSINESS', "Market research", "Extracting customer demographics, industry metrics, and pricing trends."),
        ('BUSINESS', "Competitor & SWOT analysis", "Identifying external competitive threats and detailing internal corporate strengths."),
        ('BUSINESS', "Financial analysis", "Budget forecasting, income reviews, and basic corporate balance sheets."),
        ('BUSINESS', "Email & calendar management", "Organizing corporate mail inbox, meetings, and calendar agendas."),
        ('BUSINESS', "Meeting notes & minutes", "Documenting decisions, agenda items, and task lists from online calls."),
        ('BUSINESS', "Appointment booking & travel arrangements", "Handling flight logistics, accommodations, and itinerary schedules."),
        ('BUSINESS', "Customer service support", "Assisting client base via live chat, support tickets, and email lines."),

        # MULTIMEDIA: Education & Multimedia
        ('MULTIMEDIA', "Online tutoring", "Interactive, personalized learning sessions in specialized areas."),
        ('MULTIMEDIA', "Course creation & eLearning content design", "Developing comprehensive curriculum outlines, slides, and educational guides."),
        ('MULTIMEDIA', "Lesson plan development", "Structuring class timelines, learning milestones, and resource lists."),
        ('MULTIMEDIA', "Quiz & exam creation", "Drafting assessments, tests, and homework sheets for school courses."),
        ('MULTIMEDIA', "Online form creation", "Configuring Typeform, Jotform, or Google Forms with custom layouts."),
        ('MULTIMEDIA', "eBook formatting", "Optimizing book templates for Kindle, EPUB, and PDF distributions."),
        ('MULTIMEDIA', "PDF editing & document conversion", "Editing layout text and translating between doc formats (Word to PDF, etc.)."),
        ('MULTIMEDIA', "Audio transcription", "Converting audio files into clean, readable text documents with timestamps."),
        ('MULTIMEDIA', "Video editing & subtitles", "Cutting video clips, color correcting, and overlaying subtitle scripts."),
        ('MULTIMEDIA', "Voiceover recording", "Providing clean, professional voice recordings in studio setups."),
    ]
    
    service_items = [
        ServiceItem(category=cat, title=t, short_explanation=exp)
        for cat, t, exp in services_data
    ]
    
    ServiceItem.objects.bulk_create(service_items)

def remove_services(apps, schema_editor):
    ServiceItem = apps.get_model('core', 'ServiceItem')
    ServiceItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_serviceitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_services, reverse_code=remove_services),
    ]
