# Generated by Django 6.0.5 on 2026-07-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_populate_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Tracks when the client profile/account was created', null=True),
        ),
        migrations.CreateModel(
            name='ClientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('select_service', 'Selected Service'), ('update_profile', 'Updated Profile'), ('file_upload', 'Uploaded File'), ('view_dashboard', 'Viewed Dashboard')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.clientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', 'timestamp'], name='core_client_client__e3bc95_idx'), models.Index(fields=['timestamp'], name='core_client_timesta_edec72_idx')],
            },
        ),
    ]
