# Generated by Django 6.0.5 on 2026-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clientprofile_registration_date_clientactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='project_lead_assigned',
            field=models.BooleanField(default=False, help_text='Designates if a project lead has been assigned to the client'),
        ),
    ]
