# Generated by Django 6.0.5 on 2026-07-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clientprofile_project_lead_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='assigned_lead',
            field=models.ForeignKey(blank=True, help_text='Assigned project lead (staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Services Selected'), (2, 'Team Assignment'), (3, 'Kickoff Call'), (4, 'Deliverables Begin')], default=1, help_text='Current step in the onboarding timeline'),
        ),
    ]
