# Generated by Django 6.0.5 on 2026-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clientprofile_assigned_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='deliverables_begin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Status of the deliverables beginning step', max_length=15),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='kickoff_call_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Status of the kickoff call step', max_length=15),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='services_selected_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Status of the services selection step', max_length=15),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='team_assignment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Status of the team assignment step', max_length=15),
        ),
    ]
