# Generated by Django 6.0.5 on 2026-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientprofile_deliverables_begin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last status update'),
        ),
    ]
