# Generated by Django 6.0.5 on 2026-07-17 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clientprofile_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('data_value', models.FloatField()),
                ('explanation', models.TextField()),
                ('date', models.DateField()),
                ('period_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Analytics',
                'verbose_name_plural': 'Service Analytics',
                'ordering': ['-date'],
            },
        ),
    ]
