# Generated by Django 6.0.5 on 2026-07-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_serviceanalytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceanalytics',
            old_name='data_value',
            new_name='metric_value',
        ),
        migrations.RemoveField(
            model_name='serviceanalytics',
            name='period_type',
        ),
        migrations.AddField(
            model_name='serviceanalytics',
            name='metric_name',
            field=models.CharField(default='Value', max_length=100),
        ),
    ]
