# Generated by Django 6.0.5 on 2026-07-17 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_data_value_serviceanalytics_metric_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text="Matches the ServiceItem display name (e.g. 'Graphic & Print Design').", max_length=120)),
                ('value', models.FloatField(help_text='Daily numeric value entered by the Admin (e.g. 5 videos produced).')),
                ('date', models.DateField(help_text='The calendar date this entry refers to.')),
                ('note', models.TextField(blank=True, default='', help_text='Optional Admin note / explanation for this data point.')),
                ('client', models.ForeignKey(help_text='The client this metric belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='metric_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metric Entry',
                'verbose_name_plural': 'Metric Entries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', 'service_name'], name='core_metric_client__c37f29_idx'), models.Index(fields=['date'], name='core_metric_date_75d3b4_idx')],
                'unique_together': {('client', 'service_name', 'date')},
            },
        ),
    ]
