# Generated by Django 6.0.5 on 2026-07-20 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name e.g. Video, Web, Design, Marketing', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='fas fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience Category',
                'verbose_name_plural': 'Experience Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experience_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='experience_videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL to video stream or external video link', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('technology_stack', models.CharField(blank=True, help_text='Comma separated tags e.g. Premiere Pro, 4K Cinema, Motion Graphics', max_length=200, null=True)),
                ('case_study_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.experiencecategory')),
            ],
            options={
                'verbose_name': 'Experience Item',
                'verbose_name_plural': 'Experience Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
