# Generated by Django 6.0.5 on 2026-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_experience_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio / description of the team leader', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct image URL if not using file upload', max_length=500, null=True),
        ),
    ]
