# Generated by Django 6.0.5 on 2026-07-24 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update_teammember_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metricentry',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='metricentry',
            name='core_metric_client__c37f29_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricentry',
            name='core_metric_date_75d3b4_idx',
        ),
        migrations.DeleteModel(
            name='MetricEntry',
        ),
        migrations.CreateModel(
            name='ClientMetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Daily numeric value entered by the Admin (e.g. 5 videos produced).')),
                ('date', models.DateField(help_text='The calendar date this entry refers to.')),
                ('note', models.TextField(blank=True, default='', help_text='Optional Admin note / explanation for this data point.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Tracks when the entry was created or last updated.')),
            ],
            options={
                'verbose_name': 'Client Metric Entry',
                'verbose_name_plural': 'Client Metric Entries',
                'db_table': 'core_metricentry',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='ServiceItem',
            new_name='SubService',
        ),
        migrations.AlterModelTable(
            name='subservice',
            table='core_serviceitem',
        ),
        migrations.AddField(
            model_name='clientmetricentry',
            name='client',
            field=models.ForeignKey(help_text='The client this metric belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='metric_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientmetricentry',
            name='sub_service',
            field=models.ForeignKey(help_text='The sub-service this metric belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='metric_entries', to='core.subservice'),
        ),
        migrations.AddIndex(
            model_name='clientmetricentry',
            index=models.Index(fields=['client', 'sub_service'], name='core_metric_client__bbde8c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmetricentry',
            index=models.Index(fields=['date'], name='core_metric_date_75d3b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientmetricentry',
            unique_together={('client', 'sub_service', 'date')},
        ),
    ]
