# Generated by Django 6.0.5 on 2026-07-24 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_clientmetricentry_alter_metricentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(default='fas fa-cubes', help_text='FontAwesome icon class', max_length=50)),
                ('header_image', models.URLField(blank=True, help_text='URL to professional header image', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_external_link', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='subservice',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='core.servicecategory'),
        ),
    ]
