# Generated by Django 6.0.5 on 2026-07-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_servicecategory_subservice_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='education_external_url',
            field=models.URLField(default='https://example.com', help_text='Dynamic link for Education & Multimedia card', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_phone_number',
            field=models.CharField(blank=True, default='+251 968 929 372', help_text='Phone number displayed in header (Leave empty or delete to remove)', max_length=30, null=True),
        ),
    ]
