# Generated by Django 6.0.5 on 2026-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(help_text='Project category name', max_length=100, unique=True),
        ),
    ]
