# Generated by Django 6.0.5 on 2026-07-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_create_roadmapstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='selected_services',
            field=models.ManyToManyField(blank=True, related_name='selected_by_clients', to='core.subservice'),
        ),
        migrations.AlterField(
            model_name='roadmapstep',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='DECLINED', max_length=20),
        ),
    ]
